Clean.Site/Models/NavigationViewModel.cs
using System.Reflection.Metadata;
using Umbraco.Cms.Web.Common.PublishedModels;

namespace Clean.Site.Models
{
    public class NavigationViewModel
    {
public String? HomeURL {get;set;}
public IEnumerable<NavigationItem>? NavigationItems {get;set;}
    }
}

Clean.Site/Components/NavigationViewComponent.cs
using Clean.Site.Models;
using Microsoft.AspNetCore.Mvc;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Web.Common.PublishedModels;

namespace Clean.site.Components;

[ViewComponent(Name = "Navigation")]
public class NavigationViewComponent : ViewComponent
{
    public async Task<IViewComponentResult> InvokeAsync(IPublishedContent content)
    {


        var homePage = content.AncestorOrSelf<HomePage>();
        var navigationItems = homePage?.MainNavigation ?? Enumerable.Empty<NavigationItem>();

        var model = new NavigationViewModel() {
            HomeURL = homePage.Url(),
            NavigationItems = navigationItems
        };

        return View(model);
    }
}

Clean.Site/Views/BlogPage.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.BlogPage>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
	Layout = "Master.cshtml";
}

Clean.Site/Views/Contact.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.Contact>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
	Layout = "Master.cshtml";
}

Clean.Site/Views/ContentPage.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.ContentPage>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
    Layout = "Master.cshtml";
}

<!-- Main Content-->
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        @Html.GetBlockListHtml(Model.MainContent)
    </div>
</main>

Clean.Site/Views/HomePage.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.HomePage>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
	Layout = "Master.cshtml";
}

@await Html.PartialAsync("~/Views/Partials/LatestArticles.cshtml")

Clean.Site/Views/Master.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@{
	Layout = null;
}


<!DOCTYPE html>
<html lang="en">

<head>
	@await Component.InvokeAsync("Navigation", Model)
	@await Html.PartialAsync("~/Views/Partials/metaData.cshtml")
	<link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
	<!-- Font Awesome icons (free version)-->
	<script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
	<!-- Google fonts-->
	<link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet"
		type="text/css" />
	<link
		href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
		rel="stylesheet" type="text/css" />
	<!-- Core theme CSS (includes Bootstrap)-->
	<link href="/css/styles.css" rel="stylesheet" />
</head>

<body>
	
	@await Html.PartialAsync("~/Views/Partials/navigation.cshtml")
	@await Html.PartialAsync("~/Views/Partials/header.cshtml")
	@RenderBody()
	@await Html.PartialAsync("~/Views/Partials/footer.cshtml")
	<!-- Bootstrap core JS-->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
	<!-- Core theme JS-->
	<script src="/js/scripts.js"></script>
</body>

</html>
    using SixLabors.ImageSharp.Processing;

Clean.Site/Views/Partials/LatestArticles.cshtml
@inherits UmbracoViewPage

<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->
            <div class="post-preview">
                <a href="post.html">
                    <h2 class="post-title">Man must explore, and this is exploration at its greatest</h2>
                    <h3 class="post-subtitle">Problems look mighty small from 150 miles up</h3>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#!">Start Bootstrap</a>
                    on September 24, 2023
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            <!-- Post preview-->
            <div class="post-preview">
                <a href="post.html">
                    <h2 class="post-title">I believe every human has a finite number of heartbeats. I don't intend to
                        waste any of mine.</h2>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#!">Start Bootstrap</a>
                    on September 18, 2023
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            <!-- Post preview-->
            <div class="post-preview">
                <a href="post.html">
                    <h2 class="post-title">Science has not yet mastered prophecy</h2>
                    <h3 class="post-subtitle">We predict too much for the next year and yet far too little for the next
                        ten.</h3>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#!">Start Bootstrap</a>
                    on August 24, 2023
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            <!-- Post preview-->
            <div class="post-preview">
                <a href="post.html">
                    <h2 class="post-title">Failure is not an option</h2>
                    <h3 class="post-subtitle">Many say exploration is part of our destiny, but it’s actually our duty to
                        future generations.</h3>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#!">Start Bootstrap</a>
                    on July 8, 2023
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            <!-- Pager-->
            <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts
                    →</a></div>
        </div>
    </div>
</div>

Clean.Site/Views/Partials/blocklist/Components/ImageRow.cshtml
@inherits UmbracoViewPage<BlockListItem>

@{
    var row = (ImageRow)Model.Content;
        var settings = (ImageRowSettings)Model.Settings;
    if (settings?.Hide ?? false)
    {
        return;
    }
    if(row.Image == null)
    {
        return;
    }
}

<div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
        @if(row.Link != null){
            @:<a href="@row.Link.Url" target="@row.Link.Target" title="@row.Link.Name">

        }
        <image class="img-fluid" src="@row.Image.Url()" alt="@row.Caption" />
        <span class="caption text-muted">@row.Caption</span>
        @if(row.Link != null){
            @:</a>
        }
    </div>
</div>

Clean.Site/Views/Partials/blocklist/Components/accordionRow.cshtml
@inherits UmbracoViewPage<BlockListItem>

@{
    var row = (AccordionRow)Model.Content;
    var settings = (AccordionRowSettings)Model.Settings;
    if (settings?.Hide ?? false)
    {
        return;
    }
    if (row.AccordionItems == null || !row.AccordionItems.Any())
    {
        return;
    }
    var accordionId = "accordion-" + row.Key;
}

<div class="row gx-4 gx-lg-5 pt-5 justify-content-center">

    <header class="text-center">
        <h2>@row.Title</h2>
        <p>@row.Description</p>
    </header>

    <div class="accordion" id="@accordionId">
        @{
            var index = 0;

            foreach (var item in row.AccordionItems)
            {
                var rowItem = (AccordionItem)item.Content;
                var rowSettings = (AccordionItemSettings)item.Settings;
                if (rowSettings.Hide)
                {
                    continue;
                }
                if (string.IsNullOrWhiteSpace(rowItem.Title) || rowItem.Content == null ||
                string.IsNullOrWhiteSpace(rowItem.Content.ToString()))
                {
                    continue;
                }
                var show = index == 0;
                var headingId = accordionId + "-Heading-" + index;
                var collapseId = accordionId + "-Collapse-" + index;


                <div class="accordion-item">
                    <h2 class="accordion-header" id="@headingId">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#@collapseId"
                            aria-expanded="@show" aria-controls="@collapseId">
                            @rowItem.Title
                        </button>
                    </h2>
                    <div id="@collapseId" class="accordion-collapse collapse @(show ? "show" : null)"
                        aria-labelledby="@headingId" data-bs-parent="#@accordionId">
                        <div class="accordion-body">
                            @rowItem.Content
                        </div>
                    </div>
                </div>
                index++;
            }
        }
    </div>
</div>

Clean.Site/Views/Partials/blocklist/Components/carouselRow.cshtml
@inherits UmbracoViewPage<BlockListItem>

@{
    var row = (CarouselRow)Model.Content;
    var settings = (CarouselRowSettings)Model.Settings;
    if (settings?.Hide ?? false)
    {
        return;
    }
    if (row.CarouselItems == null || !row.CarouselItems.Any())
    {
        return;
    }
    var carouselId = "carousel-" + row.Key;
}

<div id="@carouselId" class="carousel @((settings?.ShowDarMode ?? false) ? "carousel-dark" : null) slide"
    data-bs-ride="carousel">
    @if (settings?.ShowIndicators ?? false)
    {
        var itemcount = row.CarouselItems.Count();
        <div class="carousel-indicators">
            @for (var SlideIndex = 0; SlideIndex < itemcount; SlideIndex++)
            {
                var isfirst = SlideIndex == 0;
                <button type="button" data-bs-target="#@carouselId" data-bs-slide-to="@SlideIndex"
                    class="@(isfirst ? "active" : null)" aria-current="@isfirst" aria-label="Slide @(SlideIndex+1)"></button>
            }
        </div>

    }



    <div class="carousel-inner">
        @{
            var itemIndex = 0;
            foreach (var item in row.CarouselItems)
            {
                var rowItem = (CarouselItem)item.Content;
                var rowSettings = (CarouselItemSettings)item.Settings;
                if (rowSettings.Hide)
                {
                    continue;
                }

                var isfirstSlide = itemIndex == 0;
                var hastitle = !string.IsNullOrWhiteSpace(rowItem.Title);
                var hasdescription = !string.IsNullOrWhiteSpace(rowItem.Description);

                <div class="carousel-item @(isfirstSlide ? "active" : null)">
                    @if (rowItem.Image != null)
                    {
                        <img src="@rowItem.Image.GetCropUrl(width: 900, height:300)" class="d-block w-100"
                            alt="@rowItem.Image.Name">
                    }
                    @if (hasdescription || hastitle)
                    {
                        <div class="carousel-caption d-none d-md-block">
                            <h5>@rowItem.Title</h5>
                            <p>@rowItem.Description</p>
                        </div>
                    }
                </div>
                itemIndex++;
            }
        }
    </div>
    @if (settings?.ShowNavigationArrows ?? false)
    {
        <button class="carousel-control-prev" type="button" data-bs-target="#@carouselId" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#@carouselId" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    }
</div>

Clean.Site/Views/Partials/blocklist/Components/featuredItemsRow.cshtml
@inherits UmbracoViewPage<BlockListItem>

@{
    var row = (FeaturedItemsRow)Model.Content;
    var settings = (FeaturedItemsRowSettings)Model.Settings;
    if(settings?.Hide ?? false) { return; }
    if(row.FeaturedItems == null || !row.FeaturedItems.Any()) return;
}

<div class="row gx-4 gx-lg-5 justify-content-center">

    <header class="text-center">
        <h2>@row.Title</h2>
        <p>@row.Description</p>
    </header>

    @foreach(var item in row.FeaturedItems)
    {
        var rowItem = (ImageLinkItem)item.Content;
        var rowSettings = (ImageLinkItemSettings)item.Settings;
        if(rowSettings.Hide) continue;

        <div class="card col-md-4 col-sm-12">
            @if(rowItem.Image != null)
            {
                <img src="@rowItem.Image.GetCropUrl(490,383)" class="card-img-top" alt="@rowItem.Image.Name">
            }
            <div class="card-body">
                @if(!string.IsNullOrWhiteSpace(rowItem.Title))
                {
                    <h5 class="card-title">@rowItem.Title</h5>
                }
                @if(!string.IsNullOrWhiteSpace(rowItem.Description))
                {
                    <p class="card-text">@rowItem.Description</p>
                }
                @if(rowItem.Link != null)
                {
                    <a href="@rowItem.Link.Url" @rowItem.Link.Target class="btn btn-primary">@rowItem.Link.Name</a>
                }
            </div>
        </div>
    }
</div>

Clean.Site/Views/Partials/blocklist/Components/quoteRow.cshtml
@inherits UmbracoViewPage<BlockListItem>

@{
    var row = (QuoteRow)Model.Content;
    var settings = (QuoteRowSettings)Model.Settings;
    if (settings?.Hide ?? false)
    {
        return;
    }
}

<div class="row gx-4 gx-lg-5 my-5 justify-content-center bg-light text-end">
    <figure class="@(!string.IsNullOrWhiteSpace(settings?.TextAllignment) ? settings.TextAllignment : null)">
        <blockquote cite="@(row.CiteLink != null ? row.CiteLink.Url : null)">
            @row.QuoteText
        </blockquote>
        @if(!string.IsNullOrWhiteSpace(row.QuoteAuthor))
        {
        <figcaption>
            @if(!string.IsNullOrWhiteSpace(row.AuthorJobTitle)){
                @:-@(row.QuoteAuthor), <cite>@row.AuthorJobTitle</cite>
            }
            </figcaption>
        }
    </figure>
</div>

Clean.Site/Views/Partials/blocklist/Components/richTextRow.cshtml
@inherits UmbracoViewPage<BlockListItem>

@{
    var row = (RichTextRow)Model.Content;
    var settings = (RichTextRowSettings)Model.Settings;
    if (settings?.Hide ?? false)
    {
        return;
    }
    
}

<div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
        @row.Content
    </div>
</div>

Clean.Site/Views/Partials/blocklist/default.cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockListModel>
@{
    if (Model?.Any() != true) { return; }
}
<div class="umb-block-list">
    @foreach (var block in Model)
    {
        if (block?.ContentUdi == null) { continue; }
        var data = block.Content;

        @await Html.PartialAsync("blocklist/Components/" + data.ContentType.Alias, block)
    }
</div>

Clean.Site/Views/Partials/footer.cshtml
@inherits UmbracoViewPage

@{
    var homePage = Model.AncestorOrSelf<HomePage>();
}

<!-- Footer-->
<footer class="border-top">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                @if (homePage?.FooterSocialLinks != null)
                {
                    <ul class="list-inline text-center">
                        @foreach (var socialLink in homePage.FooterSocialLinks)
                        {
                            <li class="list-inline-item">
                                <a href="@socialLink.Url">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-@socialLink.Network fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        }
                    </ul>
                }

                <div class="small text-center text-muted fst-italic">&copy;
                    @Umbraco.GetDictionaryValue("Footer.CopyrightTitle") @DateTime.Now.Year</div>
            </div>
        </div>
    </div>
</footer>

Clean.Site/Views/Partials/grid/bootstrap3-fluid.cshtml
@using System.Web
@using Microsoft.AspNetCore.Html
@using Newtonsoft.Json.Linq
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<dynamic>

@*
    Razor helpers located at the bottom of this file
*@

@if (Model is JObject && Model?.sections is not null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;

    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections)
            {
                <div class="grid-section">
                    @foreach (var row in section.rows)
                    {
                        renderRow(row);
                    }
                </div>
            }
        }
        else
        {
            <div class="row clearfix">
                @foreach (var sec in Model.sections)
                {
                    <div class="grid-section">
                        <div class="col-md-@sec.grid column">
                            @foreach (var row in sec.rows)
                            {
                                renderRow(row);
                            }
                        </div>
                    </div>
                }
            </div>
        }
    </div>
}

@functions{

    private async Task renderRow(dynamic row)
    {
        <div @RenderElementAttributes(row)>
            <div class="row clearfix">
                @foreach (var area in row.areas)
                {
                    <div class="col-md-@area.grid column">
                        <div @RenderElementAttributes(area)>
                            @foreach (var control in area.controls)
                            {
                                if (control?.editor?.view != null)
                                {
                                    <text>@await Html.PartialAsync("grid/editors/base", (object)control)</text>
                                }
                            }
                        </div>
                    </div>
                 }
            </div>
        </div>
    }
}

@functions{

    public static HtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if (cfg != null)
        {
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }
        }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new HtmlString(string.Join(" ", attrs));
    }
}

Clean.Site/Views/Partials/grid/bootstrap3.cshtml
@using System.Web
@using Microsoft.AspNetCore.Html
@using Newtonsoft.Json.Linq
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<dynamic>

@if (Model is JObject && Model?.sections is not null)
{
  var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;

    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections)
            {
                <div class="grid-section">
                    @foreach (var row in section.rows)
                    {
                        renderRow(row, true);
                    }
                </div>
            }
        }
        else
        {
            <div class="container">
                <div class="row clearfix">
                    @foreach (var sec in Model.sections)
                    {
                        <div class="grid-section">
                            <div class="col-md-@sec.grid column">
                                @foreach (var row in sec.rows)
                                {
                                    renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>
        }
    </div>
}

@functions{

    private async Task renderRow(dynamic row, bool singleColumn)
    {
        <div @RenderElementAttributes(row)>
            @if (singleColumn) {
                @:<div class="container">
            }
            <div class="row clearfix">
                @foreach (var area in row.areas)
                {
                    <div class="col-md-@area.grid column">
                        <div @RenderElementAttributes(area)>
                            @foreach (var control in area.controls)
                            {
                                if (control?.editor?.view != null)
                                {
                                    <text>@await Html.PartialAsync("grid/editors/base", (object)control)</text>
                                }
                            }
                        </div>
                    </div>
                 }
            </div>
            @if (singleColumn) {
                @:</div>
            }
        </div>
    }

}

@functions{

    public static HtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if (cfg != null)
        {
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }
        }

        JObject style = contentItem.styles;

        if (style != null)
        {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style=\"" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "\"");
        }

        return new HtmlString(string.Join(" ", attrs));
    }
}

Clean.Site/Views/Partials/grid/editors/base.cshtml
@model dynamic

@try
{
    string editor = EditorView(Model);
    <text>@await Html.PartialAsync(editor, Model as object)</text>
}
catch (Exception ex)
{
    <pre>@ex.ToString()</pre>
}

@functions{

    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.Replace(".html", ".cshtml");

        if (!view.Contains("/"))
        {
            view = "grid/editors/" + view;
        }

        return view;
    }
}

Clean.Site/Views/Partials/grid/editors/embed.cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<dynamic>

@if (Model is not null)
{
  string embedValue = Convert.ToString(Model.value);
  embedValue = embedValue.DetectIsJson() ? Model.value.preview : Model.value;

  <div class="video-wrapper">
    @Html.Raw(embedValue)
  </div>
}

Clean.Site/Views/Partials/grid/editors/macro.cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<dynamic>

@if (Model?.value is not null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    var parameters = new Dictionary<string,object>();
    foreach (var mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @await Umbraco.RenderMacroAsync(macroAlias, parameters)
    </text>
}

Clean.Site/Views/Partials/grid/editors/media.cshtml
@model dynamic
@using Umbraco.Cms.Core.Media
@using Umbraco.Cms.Core.PropertyEditors.ValueConverters
@inject IImageUrlGenerator ImageUrlGenerator

@if (Model?.value is not null)
{
    var url = Model.value.image;

    if (Model.editor.config != null && Model.editor.config.size != null)
    {
        if (Model.value.coordinates != null)
        {
            url = ImageCropperTemplateCoreExtensions.GetCropUrl(
                (string)url,
                ImageUrlGenerator,
                width: (int)Model.editor.config.size.width,
                height: (int)Model.editor.config.size.height,
                cropAlias: "default",
                cropDataSet: new ImageCropperValue
                {
                    Crops = new[]
                    {
                        new ImageCropperValue.ImageCropperCrop
                        {
                            Alias = "default",
                            Coordinates = new ImageCropperValue.ImageCropperCropCoordinates
                            {
                                X1 = (decimal)Model.value.coordinates.x1,
                                Y1 = (decimal)Model.value.coordinates.y1,
                                X2 = (decimal)Model.value.coordinates.x2,
                                Y2 = (decimal)Model.value.coordinates.y2
                            }
                        }
                    }
                });
        }
        else
        {
            url = ImageCropperTemplateCoreExtensions.GetCropUrl(
                (string)url,
                ImageUrlGenerator,
                width: (int)Model.editor.config.size.width,
                height: (int)Model.editor.config.size.height,
                cropDataSet: new ImageCropperValue
                {
                    FocalPoint = new ImageCropperValue.ImageCropperFocalPoint
                    {
                        Top = Model.value.focalPoint == null ? 0.5m : Model.value.focalPoint.top,
                        Left = Model.value.focalPoint == null ? 0.5m : Model.value.focalPoint.left
                    }
                });
        }
    }

    var altText = Model.value.altText ?? Model.value.caption ?? string.Empty;

    <img src="@url" alt="@altText">

    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

Clean.Site/Views/Partials/grid/editors/rte.cshtml
@using Umbraco.Cms.Core.Templates
@model dynamic
@inject HtmlLocalLinkParser HtmlLocalLinkParser;
@inject HtmlUrlParser HtmlUrlParser;
@inject HtmlImageSourceParser HtmlImageSourceParser;

@{
    var value = HtmlLocalLinkParser.EnsureInternalLinks(Model?.value.ToString());
    value = HtmlUrlParser.EnsureUrls(value);
    value = HtmlImageSourceParser.EnsureImageSources(value);
}

@Html.Raw(value)

Clean.Site/Views/Partials/grid/editors/textstring.cshtml
@using System.Web
@model dynamic

@if (Model?.editor.config.markup is not null)
{
    string markup = Model.editor.config.markup.ToString();
    markup = markup.Replace("#value#", Html.ReplaceLineBreaks((string)Model.value.ToString()).ToString());

    if (Model.editor.config.style != null)
    {
        markup = markup.Replace("#style#", Model.editor.config.style.ToString());
    }

    <text>
        @Html.Raw(markup)
    </text>
}
else
{
    <text>
        <div style="@Model?.editor.config.style">@Model?.value</div>
    </text>
}

Clean.Site/Views/Partials/header.cshtml
@inherits UmbracoViewPage<IHeaderProperties>

<!-- Page Header-->
<header class="masthead" style="background-image: url('@Model.Headerimage.Url()')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>@Model.Title</h1>
                    <span class="subheading">@Model.Subtitle</span>
                </div>
            </div>
        </div>
    </div>
</header>

Clean.Site/Views/Partials/metaData.cshtml
@inherits UmbracoViewPage<IHeaderProperties>

<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<meta name="description" content="" />
<meta name="author" content="" />
<title>@Model.Title</title>